name: motor_diary
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  camera:
  image_picker:
  firebase_auth:
  firebase_core:
  firebase_database:
  odometer:
  pytorch_mobile:
  sqflite:
  path:
  path_provider:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: ds_digital
      fonts:
        - asset: fonts/DS-DIGIT.TTF