// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbLNNBN3g1dTIdDditcC-pEuzQ6aSz6eI',
    appId: '1:429554201303:web:93bf1f203a9bebd6cf3692',
    messagingSenderId: '429554201303',
    projectId: 'usth-aa33f',
    authDomain: 'usth-aa33f.firebaseapp.com',
    storageBucket: 'usth-aa33f.appspot.com',
    measurementId: 'G-F80KC6EB1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxiAtvuzOfnpUtx9hbwrAJNjJTMlUO6Y',
    appId: '1:429554201303:android:7c6114c0deb6e56acf3692',
    messagingSenderId: '429554201303',
    projectId: 'usth-aa33f',
    storageBucket: 'usth-aa33f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdy2tgfEmp_DbpBEu_L_Qgupe1khS29UA',
    appId: '1:429554201303:ios:d23c5d22c95d6e12cf3692',
    messagingSenderId: '429554201303',
    projectId: 'usth-aa33f',
    storageBucket: 'usth-aa33f.appspot.com',
    iosBundleId: 'com.example.motorDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdy2tgfEmp_DbpBEu_L_Qgupe1khS29UA',
    appId: '1:429554201303:ios:d23c5d22c95d6e12cf3692',
    messagingSenderId: '429554201303',
    projectId: 'usth-aa33f',
    storageBucket: 'usth-aa33f.appspot.com',
    iosBundleId: 'com.example.motorDiary',
  );
}
